
from os import environ as osEnviron
from pathlib import Path
from typing import Any
from typing import Dict
from typing import Optional
from typing import Tuple

from logging import DEBUG

from unittest import TestSuite
from unittest import main as unitTestMain


from networkx import Graph
import matplotlib.pyplot as plt
from networkx import read_gml
from matplotlib.testing.compare import compare_images
from matplotlib.image import imread as imageRead
from matplotlib.pyplot import subplots as plotSubplots
from matplotlib.pyplot import show as plotShow
from matplotlib.pyplot import tight_layout as plotTightLayout

from orthogonal.topologyShapeMetric.Compaction import Compaction
from orthogonal.topologyShapeMetric.Orthogonalization import Orthogonalization
from orthogonal.topologyShapeMetric.Planarization import Planarization

from codeallybasic.ResourceManager import ResourceManager
from tests.ProjectTestBase import ProjectTestBase

OUTPUT_DIR: Path = Path('/tmp')

GOLDEN_IMAGES_PATH: Path        = Path('tests') / 'resources' / 'goldenimages'
GOLDEN_IMAGES_PACKAGE_NAME: str = 'tests.resources.goldenimages'

CASE1_PNG: str = 'case1.png'
CASE2_PNG: str = 'case2.png'
SIMPLE_PNG: str = 'simple.png'

CASE1_BICONNECTED_PNG: str = 'case1BiConnected.png'
CASE2_BICONNECTED_PNG: str = 'case2BiConnected.png'

TRANSLATION_GRAPH_SIMPLE_PNG:  str = 'translationGraphSimple.png'
TRANSLATION_GRAPH_COMPLEX_PNG: str = 'translationGraphComplex.png'
TRANSLATION_GRAPH_MEDIUM_PNG:  str = 'translationGraphMedium.png'


class TestGML(ProjectTestBase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    @classmethod
    def retrieveGoldenImagePath(cls, bareFileName: str) -> Path:
        fqFileName: str = ResourceManager.retrieveResourcePath(
            bareFileName=bareFileName,
            resourcePath=str(GOLDEN_IMAGES_PATH),
            packageName=GOLDEN_IMAGES_PACKAGE_NAME,
        )
        return Path(fqFileName)

    @classmethod
    def _showVisualDiffGui(cls, testName: str, goldenPath: Path, generatedPath: Path, diffPath: Path):
        """
        Display an interactive three-panel GUI comparison of golden, generated, and difference images.

        When running in a continuous integration environment (indicated by the presence of the 'CI'
        environment variable), this method exits early to ensure headless execution without attempting
        to attach to a display server.

        Args:
            testName: Identifier of the test case experiencing the image mismatch.
            goldenPath: Filesystem path to the golden benchmark image.
            generatedPath: Filesystem path to the newly generated test output image.
            diffPath: Filesystem path to the visual difference mask generated by compare_images.
        """
        if 'CI' in osEnviron:
            return

        fig: Any
        axes: Any
        fig, axes = plotSubplots(1, 3, figsize=(15, 5))
        if fig.canvas.manager is not None:
            fig.canvas.manager.set_window_title(f'Visual Diff: {testName}')

        axes[0].imshow(imageRead(str(goldenPath)))
        axes[0].set_title('Golden (Expected)')
        axes[1].imshow(imageRead(str(generatedPath)))
        axes[1].set_title('Generated (Actual)')
        axes[2].imshow(imageRead(str(diffPath)))
        axes[2].set_title('Difference')

        ax: Any
        for ax in axes:
            ax.axis('off')

        plotTightLayout()
        plotShow()

    def setUp(self):
        super().setUp()

    def testCase1(self):

        fqFileName: str   = TestGML.retrieveResourcePath('case1.gml')
        graph:      Graph = Graph(read_gml(fqFileName))

        compact: Compaction = self._generate(graph, {node: eval(node) for node in graph})

        compact.draw()
        self._verifyImage('testCase1', CASE1_PNG)

    def testCase1BiConnected(self):

        fqFileName: str   = TestGML.retrieveResourcePath("case1BiConnected.gml")
        G:          Graph = Graph(read_gml(fqFileName))
        compact: Compaction = self._generate(G, {node: eval(node) for node in G})

        compact.draw()
        self._verifyImage('testCase1BiConnected', CASE1_BICONNECTED_PNG)

    def testCase2(self):

        fqFileName: str        = TestGML.retrieveResourcePath("case2.gml")
        G:          Graph      = Graph(read_gml(fqFileName))
        compact:    Compaction = self._generate(G, {node: eval(node) for node in G})

        compact.draw()
        self._verifyImage('testCase2', CASE2_PNG)

        if self.logger.level == DEBUG:
            for flowKey in compact.flow_dict.keys():
                self.logger.debug(f'{flowKey=} - {compact.flow_dict[flowKey]=}')

    def testCase2BiConnected(self):

        fqFileName: str        = TestGML.retrieveResourcePath("case2BiConnected.gml")
        G:          Graph      = Graph(read_gml(fqFileName))
        compact:    Compaction = self._generate(G, {node: eval(node) for node in G})

        compact.draw()
        self._verifyImage('testCase2BiConnected', CASE2_BICONNECTED_PNG)

    def testSimple(self):

        fqFileName: str   = TestGML.retrieveResourcePath("simple.gml")
        G:          Graph = Graph(read_gml(fqFileName))

        if self.logger.level == DEBUG:
            for node in G:
                self.logger.debug(f'{node=}')

        compact: Compaction = self._generate(G, {node: eval(node) for node in G})

        for flowKey in compact.flow_dict.keys():
            valueDict = compact.flow_dict[flowKey]
            self.logger.debug(f'{flowKey=} - {valueDict}=')
            if self.logger.level == DEBUG:
                for valueKey in valueDict.keys():
                    self.logger.info(f'\t\t{valueKey=} {valueDict[valueKey]=}')

        compact.draw(with_labels=True)
        self._verifyImage('testSimple', SIMPLE_PNG)

    def testTranslationGraphSimple(self):

        fqFileName: str   = TestGML.retrieveResourcePath("translationGraphSimple.gml")
        G:          Graph = Graph(read_gml(fqFileName))

        self.logger.debug(f'{G.nodes=}')
        positionDictionary: Dict[str, Tuple] = {}
        for node in G:
            self.logger.debug(f'{node=}')
            x: int = G.nodes[node]['graphics']['x']
            y: int = G.nodes[node]['graphics']['y']
            positionDictionary[node] = (x, y)

        plt.xkcd()
        compact: Compaction = self._generate(G, positionDictionary)

        compact.draw(with_labels=True)
        self._verifyImage('testTranslationGraphSimple', TRANSLATION_GRAPH_SIMPLE_PNG)

    def testTranslationGraphComplex(self):

        fqFileName: str   = TestGML.retrieveResourcePath("translationGraphComplex.gml")
        G:          Graph = Graph(read_gml(fqFileName))

        positionDictionary: Dict[str, Tuple] = {}
        for node in G:
            self.logger.debug(f'{node=}')
            x: int = G.nodes[node]['graphics']['x']
            y: int = G.nodes[node]['graphics']['y']
            positionDictionary[node] = (x, y)

        compact: Compaction = self._generate(G, positionDictionary)
        plt.xkcd()
        compact.draw(with_labels=True)

        self._verifyImage('testTranslationGraphComplex', TRANSLATION_GRAPH_COMPLEX_PNG)

    def testTranslationGraphMedium(self):

        fqFileName: str   = TestGML.retrieveResourcePath("translationGraphMedium.gml")
        G:          Graph = Graph(read_gml(fqFileName))

        positionDictionary: Dict[str, Tuple] = {}
        for node in G:
            self.logger.debug(f'{node=}')
            x: int = G.nodes[node]['graphics']['x']
            y: int = G.nodes[node]['graphics']['y']
            positionDictionary[node] = (x, y)

        plt.xkcd()
        compact: Compaction = self._generate(G, positionDictionary)
        compact.draw(with_labels=True)
        self._verifyImage('testTranslationGraphMedium', TRANSLATION_GRAPH_MEDIUM_PNG)

    def _verifyImage(self, testName: str, imageName: str):
        """
        Save the current plot and verify it matches the golden benchmark image.

        Args:
            testName: Identifier of the test case executing the verification.
            imageName: Bare filename of the target image artifact.
        """
        generatedImagePath: Path = OUTPUT_DIR / imageName
        plt.savefig(generatedImagePath)

        goldenImagePath: Path = TestGML.retrieveGoldenImagePath(imageName)
        self._assertBinaryEqual(testName, generatedImagePath, goldenImagePath)

    def _assertBinaryEqual(self, testName: str, generatedFilePath: Path, goldenFilePath: Path):

        diffResult: Optional[Any] = compare_images(
            expected=str(goldenFilePath),
            actual=str(generatedFilePath),
            tol=0,
        )
        if diffResult is not None:
            print(f'\n{diffResult}')
            diffPath: Path = generatedFilePath.with_name(f'{generatedFilePath.stem}-failed-diff.png')
            if diffPath.exists():
                TestGML._showVisualDiffGui(testName, goldenFilePath, generatedFilePath, diffPath)

        failureMessage: str = (
            f'{testName}:\n'
            f'Binary mismatch for {generatedFilePath.name}'
        )

        self.assertIsNone(diffResult, failureMessage)

    def _generate(self, G, pos=None) -> Compaction:

        planar:     Planarization     = Planarization(G, pos)
        orthogonal: Orthogonalization = Orthogonalization(planar)
        compact:    Compaction        = Compaction(orthogonal)

        return compact


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestGML))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
