graph [
	directed 1
	version  1.0
	label "GML for DefaultGraphName"
	comment "Generated by Pyut Version 4.0"
	node [
		id 66
		label "Class0"
		graphics [
			x 99.0
			y 76.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 67
		label "Class1"
		graphics [
			x 307.0
			y 67.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 68
		label "Class2"
		graphics [
			x 538.0
			y 54.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 69
		label "Class3"
		graphics [
			x 168.0
			y 426.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 70
		label "Class4"
		graphics [
			x 530.0
			y 410.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 71
		label "Class5"
		graphics [
			x 737.0
			y 253.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 72
		label "Class6"
		graphics [
			x 852.0
			y 93.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 73
		label "Class7"
		graphics [
			x 946.0
			y 416.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 74
		label "Class8"
		graphics [
			x 803.0
			y 423.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 75
		label "Class9"
		graphics [
			x 679.0
			y 543.0
			z 0
			w 100.0
			h 100.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	edge [
		id 78
		source 69
		target 66
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 218.0
					y 426.0
					z 0.0
				]
				point [
					x 149.0
					y 175.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 93
		source 67
		target 66
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 307.0
					y 117.0
					z 0.0
				]
				point [
					x 198.0
					y 126.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 81
		source 67
		target 68
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 406.0
					y 117.0
					z 0.0
				]
				point [
					x 538.0
					y 104.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 87
		source 67
		target 70
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 357.0
					y 166.0
					z 0.0
				]
				point [
					x 580.0
					y 410.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 96
		source 68
		target 71
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 588.0
					y 153.0
					z 0.0
				]
				point [
					x 787.0
					y 253.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 102
		source 72
		target 68
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 852.0
					y 143.0
					z 0.0
				]
				point [
					x 637.0
					y 104.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 105
		source 75
		target 71
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 729.0
					y 543.0
					z 0.0
				]
				point [
					x 787.0
					y 352.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 108
		source 74
		target 71
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 853.0
					y 423.0
					z 0.0
				]
				point [
					x 787.0
					y 352.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 111
		source 73
		target 71
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 946.0
					y 466.0
					z 0.0
				]
				point [
					x 836.0
					y 303.0
					z 0.0
				]
			]
		]
	]
]