graph [
	directed 1
	version  1.0
	label "GML for DefaultGraphName"
	comment "Generated by Pyut Version 4.0"
	node [
		id 50
		label "Severity"
		graphics [
			x 577.0
			y 40.0
			z 0
			w 142.0
			h 84.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 51
		label "TestResults"
		graphics [
			x 9.0
			y 8.0
			z 0
			w 137.0
			h 40.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 52
		label "TestSuiteRun"
		graphics [
			x 47.0
			y 237.0
			z 0
			w 138.0
			h 40.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 53
		label "TestCaseRun"
		graphics [
			x 256.0
			y 45.0
			z 0
			w 134.0
			h 50.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 54
		label "VariationRun"
		graphics [
			x 561.0
			y 219.0
			z 0
			w 101.0
			h 50.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 55
		label "TestRun"
		graphics [
			x 234.0
			y 418.0
			z 0
			w 50.0
			h 50.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	edge [
		id 70
		source 53
		target 50
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 389.0
					y 64.0
					z 0.0
				]
				point [
					x 577.0
					y 82.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 82
		source 54
		target 50
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 612.0
					y 219.0
					z 0.0
				]
				point [
					x 665.0
					y 123.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 58
		source 51
		target 52
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 81.0
					y 47.0
					z 0.0
				]
				point [
					x 102.0
					y 237.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 64
		source 52
		target 53
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 184.0
					y 252.0
					z 0.0
				]
				point [
					x 256.0
					y 70.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 88
		source 55
		target 52
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 234.0
					y 443.0
					z 0.0
				]
				point [
					x 113.0
					y 276.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 76
		source 53
		target 54
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 351.0
					y 94.0
					z 0.0
				]
				point [
					x 561.0
					y 243.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 91
		source 55
		target 53
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 252.0
					y 418.0
					z 0.0
				]
				point [
					x 323.0
					y 94.0
					z 0.0
				]
			]
		]
	]
	edge [
		id 94
		source 55
		target 54
		graphics [
			type "line"
			arrow "last"
			Line [
				point [
					x 283.0
					y 447.0
					z 0.0
				]
				point [
					x 580.0
					y 268.0
					z 0.0
				]
			]
		]
	]
]